package com.bt.nat.capabilities.wsdl.managenetworkandservicediagnostics._2007._08._01;

import java.io.FileOutputStream;

import javax.jws.WebService;
import javax.xml.bind.JAXB;
import javax.xml.bind.JAXBContext;
import javax.xml.ws.BindingType;

import com.bt.nat.afm.linetest.types.GetBaselineTestResultByServiceIdRequest;
import com.bt.nat.afm.linetest.types.GetBaselineTestResultByServiceIdResponse;
import com.bt.nat.afm.linetest.types.GetSummaryByServiceIdRequest;
import com.bt.nat.afm.linetest.types.GetSummaryByServiceIdResponse;
import com.bt.nat.afm.linetest.types.GetTestResultByMortIdRequest;
import com.bt.nat.afm.linetest.types.GetTestResultByMortIdResponse;
import com.bt.nat.afm.linetest.types.GetTestResultByTestIdRequest;
import com.bt.nat.afm.linetest.types.GetTestResultByTestIdResponse;

/**
 * This class was generated by the JAX-WS RI. Oracle JAX-WS 2.1.5 Generated
 * source version: 2.1
 * 
 */
@WebService(portName = "GetTestResultPort", serviceName = "GetTestResultService", targetNamespace = "http://capabilities.nat.bt.com/wsdl/ManageNetworkAndServiceDiagnostics/2007/08/01", wsdlLocation = "/wsdls/MYWSDL.wsdl", endpointInterface = "com.bt.nat.capabilities.wsdl.managenetworkandservicediagnostics._2007._08._01.GetTestResultPort")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class GetTestResultService_GetTestResultPortImpl implements
		GetTestResultPort {

	public GetTestResultService_GetTestResultPortImpl() {
	}

	/**
	 * 
	 * @param input
	 * @return returns
	 *         com.bt.nat.afm.linetest.types.GetTestResultByTestIdResponse
	 */
	public GetTestResultByTestIdResponse getTestResultByTestId(
			GetTestResultByTestIdRequest input) {
		// replace with your impl here
		return null;
	}

	/**
	 * 
	 * @param input
	 * @return returns
	 *         com.bt.nat.afm.linetest.types.GetTestResultByMortIdResponse
	 */
	public GetTestResultByMortIdResponse getTestResultByMortId(
			GetTestResultByMortIdRequest input) {
		// replace with your impl here
		GetTestResultByMortIdResponse response=new GetTestResultByMortIdResponse();
		
		return null;
	}

	/**
	 * 
	 * @param input
	 * @return returns
	 *         com.bt.nat.afm.linetest.types.GetSummaryByServiceIdResponse
	 */
	public GetSummaryByServiceIdResponse getSummaryByServiceId(
			GetSummaryByServiceIdRequest input) {
		// replace with your impl here
		return null;
	}

	/**
	 * 
	 * @param input
	 * @return returns
	 *         com.bt.nat.afm.linetest.types.GetBaselineTestResultByServiceIdResponse
	 */
	public GetBaselineTestResultByServiceIdResponse getBaselineTestResultByServiceId(
			GetBaselineTestResultByServiceIdRequest input) {
		// replace with your impl here
		return null;
	}

}
